### ISSUE TITLE
Treinamento de git

### ISSUE THREAD

**Issue by andrewlucasgs** [fga-eps-mds/2019.2-Grupo2#1]
## Objetivo
Relaizar um dojo de git para nivelar o conhecimento da equipe em git.

## Roteiro
- [x] Apresentar conceitos básicos git;
- [x] Mostrar, na prática, como contribuir em um projeto do github. (com resolução de conflitos).

**O dojo será ministrado pela @nahmrodrigues no dia 24/08/2019.**

**Comment by nahmrodrigues** [comment]
Link da apresentação: https://docs.google.com/presentation/d/1viXmQ9tnydTBsZw9oxwOXB5fvBs6IaLcUljPzVyBeoQ/edit?usp=sharing

**Comment by nahmrodrigues** [comment]
Referências:

- https://rogerdudler.github.io/git-guide/index.pt_BR.html
- https://tableless.com.br/tudo-que-voce-queria-saber-sobre-git-e-github-mas-tinha-vergonha-de-perguntar/

**Comment by nahmrodrigues** [comment]
Repositório utilizado no treinamento: https://github.com/nahmrodrigues/dojo-git
