### ISSUE TITLE
S08 - Treinamento de Gitflow

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Grupo2#13]
## Objetivo

Fornecer ao time a padronização adotada por meio do GitFlow, definindo fluxo de trabalho e nomenclaturas a serem utilizadas.

## Critérios de Aceitação

- [x]  Apresentar características do gitflow que serão incorporadas ao projeto
- [x]  Mostrar exemplos de como seria a padronização da criação de branches

**Comment by drianne** [comment]
**Treinamento ministrado no dia 31/08/2019 por @nahmrodrigues **

**Comment by nahmrodrigues** [comment]
Referências:

* https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
* https://fjorgemota.com/git-flow-uma-forma-legal-de-organizar-repositorios-git/

**Comment by nahmrodrigues** [comment]
Documento gerado: https://hackmd.io/s/rk5lkC5SH
