### ISSUE TITLE
S09 - Treinamento de Docker

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Grupo2#14]
## Objetivo

Fornecer ao time noções básicas de Docker.

## Critérios de Aceitação

- [x] Explicar noções teóricas básicas de Docker
- [x] Apresentar como instalar a ferramenta
- [x] Mostrar na prática como utilizar o docker para subir ambiente, etc

**Comment by drianne** [comment]
**Treinamento realizado por @andrewlucasgs no dia 31/08/2019**

**Comment by andrewlucasgs** [comment]
Foi instalado e apresentado as tecnologias Docker e docker-compose.
