### ISSUE TITLE
S10 - Treinamento de Bancos de Dados

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Grupo2#15]
## Objetivo
Fornecer conhecimento básico a respeito dos conceitos de banco que serão necessários ao time de desenvolvimento.

## Roteiro
- [x] Mostrar conceitos básicos de criação de tabelas e relações
- [x] Apresentar técnicas básicas de normalização

**Comment by drianne** [comment]
**O dojo foi ministrado por @andrewlucasgs  no dia 31/08/2019.**

**Comment by andrewlucasgs** [comment]
Foi aprensentado o funcionamento basico de um banco de dados, e como modelar os dados de um problema.
