### ISSUE TITLE
S11 - Estudo de Conceitos Financeiros

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Grupo2#16]
## Objetivo
Conhecer as terminologias, domínio da aplicação, assim como a legislação envolvida, considerando a burocracia existente no mecanismo do cheque especial. 

## Roteiro
- [ ] O que é um cheque especial 
- [ ] Porque o cheque especial existe
- [ ] Quais os tipos/instituições aceitam esse serviço
- [ ] Em que tipo de situação é possível utilizar esse serviço
- [ ] Quando é possível adquirir esse serviço 
- [ ] Qual o custo do uso desse serviço nas instituições (taxas, etc)

## Critérios de Aceitação
- [x] Todos os componentes da equipe anexaram os principais links utilizados para estudo

**Comment by ErickCReis** [comment]
Resumo básico: https://www.bompracredito.com.br/blog/o-que-e-cheque-especial

**Comment by mlfaa** [comment]
Achei interessante esse site, pois ele realiza empréstimos online, o que pode ser uma ideia de parte da solução do problema proposto para o grupo:  https://www.geru.com.br/emprestimos/sobre-nos/

**Comment by isabellacgmsa** [comment]
Achei válido analisar os sistemas propostos por outro bancos para ver similaridades e/ou diferenças entre os mesmos:

https://www.bb.com.br/pbb/pagina-inicial/voce/produtos-e-servicos/emprestimo/emprestimo-pessoal/cheque-especial#/

https://www.itau.com.br/creditos-financiamentos/cheque-especial/

http://www.caixa.gov.br/voce/credito-financiamento/credito-pessoal/cheque-especial/Paginas/default.aspx

https://banco.bradesco/html/classic/produtos-servicos/emprestimo-e-financiamento/cheque-especial.shtm

https://portal.brb.com.br/para-voce/emprestimos-e-financiamentos/correntista/cheque-especial-brasilia

**Comment by isabellacgmsa** [comment]
Para o caso de surgimento, durante o trabalho, de termos bancários que não são de conhecimento do grupo achei interessante esse link:

https://apps.univesp.br/100-conceitos-financeiros/

**Comment by BielLopes2000** [comment]
https://www.bb.com.br/pbb/pagina-inicial/voce/produtos-e-servicos/emprestimo/emprestimo-pessoal/cheque-especial#/

https://www.serasaconsumidor.com.br/ensina/seu-credito/como-funciona-o-cheque-especial/

https://www.serasaconsumidor.com.br/ensina/dicas/novas-regras-do-cheque-especial/

https://www.youtube.com/watch?time_continue=43&v=ByiNh1qmM14

https://www.youtube.com/watch?v=vk9_O3_PWNY

**Comment by nahmrodrigues** [comment]
Achei interessante também entender o contexto da organização financeira no Brasil, quem pode fazer o quê, etc. Segue o link do site do Banco Central, que usei como referência:

- https://www.bcb.gov.br/estabilidadefinanceira/sfn

**Comment by JongaMatos** [comment]
https://www.bidu.com.br/credito/emprestimo-pessoal/o-que-e-cheque-especial/
https://www.serasaconsumidor.com.br/ensina/seu-credito/como-funciona-o-cheque-especial/
https://www.bompracredito.com.br/blog/o-que-e-cheque-especial
https://www.bb.com.br/pbb/pagina-inicial/voce/produtos-e-servicos/emprestimo/emprestimo-pessoal/cheque-especial#/

**Comment by drianne** [comment]
Esse link é interessante para observar os conceitos básicos : https://www.serasaconsumidor.com.br/ensina/seu-credito/como-funciona-o-cheque-especial/
https://www.bcb.gov.br/pre/pef/port/glossario_cidadania_financeira.pdf

**Comment by andrewlucasgs** [comment]
Esse link é interessante para entender como funciona o overdraft na N26 europa.
https://support.n26.com/en-de/get-more-out-of-n26/overdraft
https://n26.com/en-gb/overdraft

**Comment by Coredoisquad** [comment]
Achei esses dois sites interessantes sobre overdraft, explicam bem como funciona e em um deles explica um pouco mais sobre os tipos e também fala sobre as taxas

https://www.moneyadviceservice.org.uk/en/articles/overdrafts-explained
https://www.investopedia.com/terms/o/overdraft.asp

**Comment by LuizaCezario** [comment]
Alguns conceitos sobre cheque especial e como funciona e um link sobre a n26
https://www.serasaconsumidor.com.br/ensina/seu-credito/como-funciona-o-cheque-especial/
https://www.itau.com.br/creditos-financiamentos/cheque-especial/
https://www.eurodicas.com.br/banco-n26/
