### ISSUE TITLE
D06 - Criar template de issue

### ISSUE THREAD

**Issue by andrewlucasgs** [fga-eps-mds/2019.2-Grupo2#17]
## Objetivo
Criar um padrão para as issues do projeto.

## Roteiro
- [x] Qual titulo colocar.
- [x] Quais labels adicionar.
- [x] Qual template usar na issue.

## Critérios de Aceitação
- [ ] Adicionar ao repositório a documentação do template em markdown.

**Comment by drianne** [comment]
This issue was solved and the templates are in .github paste.
