### ISSUE TITLE
D08 - Criar template de pull request

### ISSUE THREAD

**Issue by andrewlucasgs** [fga-eps-mds/2019.2-Grupo2#19]
## Objetivo
Criar um template a ser seguindo na abretura de um pull request.

## Roteiro
- [ ] Criar documento com padrão a ser seguindo para abertura de PR

## Critérios de Aceitação
- [x] Adicionar ao repositório o template de PR

**Comment by drianne** [comment]
O template se encontra na pasta .github.

**Comment by drianne** [comment]
@andrewlucasgs  esse documento com o padrão a ser seguido para a abertura do PR é o próprio contributing?

**Comment by andrewlucasgs** [comment]
Sim
