### ISSUE TITLE
M01 - Reunião com o cliente

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Grupo2#20]
## Objetivo
Reunião com o cliente para o entendimento do projeto. A reunião ocorreu no dia 02 de setembro de 2019, com a presença dos membros de EPS: Adrianne, Andrew e Maria Luiza.

## Resultados
- Estudo sobre meios de pagamento
- O sistema consistirá no desenvolvimento de um aplicativo mobile
- A priori os dados serão mocados, pois não terá uma API disponível por parte do cliente
- A priori a tecnologia será decida pelo grupo

**Comment by drianne** [comment]
Finalizando a issue visto que o objetivo da reunião foi alcançado e pode nos dar ideia dos próximos passos a serem feitos.
