### ISSUE TITLE
D11 - Delinear entidades do projeto

### ISSUE THREAD

**Issue by nahmrodrigues** [fga-eps-mds/2019.2-Grupo2#29]
## Descrição da Mudança *
Mapear entidades principais para o desenvolvimento do sistema e elaborar diagramas de classe e lógico (banco de dados)

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Mapear entidades do sistema 
- [x] Criar diagrama de classes
- [x] Criar diagrama  lógico

## Critérios de Aceitação * 

- [x] Diagrama de classes
- [x] Diagrama lógico
- [x] Os dois diagramas devem estar presentes no Documento de Arquitetura, com as descrições apropriadas

**Comment by drianne** [comment]
Os diagramas estão presentes no documento.

**Comment by nahmrodrigues** [comment]
Foram elaborados o diagrama de classes e o diagrama lógico, que podem ser encontrados em: https://fga-eps-mds.github.io/2019.2-Over26/#/architecture
